Add installation script
goatfiles/dotfiles pull request #13
Opened 2022-09-29 11:52 UTC by atxr

I recently finished the script to install the config on a fresh arch installation
There are two points I want to talk about with you:
- I didn't add anything in a README, because I add some issues with `curl`
- I clone my fork in the script and not you repo. I don't know how to deal with that, maybe an arguement that specify the repo/branch to use for the dotfile can be a nice feature

I tested it on arch, and will probably fix few bugs/missing dependencies soon

2022-09-29 12:46 UTC, amtoine commented
it's super weird i'm the author of these commits :laughing: 
anyways :eyes:

2022-09-29 16:38 UTC, atxr commented
> it's super weird i'm the author of these commits laughing anyways eyes

Yes! Actually you pushed your git config so when I'm working on the main branch, I'm you :eyes: 
That's an issue we should tackle next

2022-09-30 12:38 UTC, amtoine commented
> Yes! Actually you pushed your git config so when I'm working on the main branch, I'm you :eyes: 
>
ooooh you're right :scream:

> That's an issue we should tackle next
>
definitely then :thinking:

2022-09-30 18:10 UTC, amtoine requested changes
a few things to remove and change,
but that's great otherwise :+1: 

we will make the script fancier in the future, with colors, logging, echoing, prompts and stuff :wink: :muscle:

2022-09-30 18:10 UTC, amtoine commented on .xinitrc
> +#!/bin/sh
i do not get the point of adding this file here :thinking: 
you `systemctl enable sddm`  in `install.sh` so no need to add an `.xinitrc` file here :confused: 

and i moved my `.xinitrc` to `.config/X11/xinitrc` :wink: 
could you please remove this one? :yum:

2022-09-30 18:10 UTC, amtoine commented on install.sh
> +./install.sh x86_64/paru x86_64/amtoine-scripts-git/ x86_64/amtoine-sounds-git/ x86_64/amtoine-wallpapers-git/ x86_64/amtoine-applications-git/ x86_64/amtoine-icons-git/
could you make that a multi-line?
i think it would be much easier to get the gist of the global list of custom packages we install here :yum:

2022-09-30 18:10 UTC, amtoine commented on install.sh
> +cd
in order to avoid calling `cd ...` and then a "return" `cd`, you should use the
```bash
(
    cd ...
    ...
)
```
structure! :yum: 

it is a subshell, so it automatically gets back to its previous location in `bash` :ok_hand:

2022-09-30 18:10 UTC, amtoine commented on install.sh
> +sudo rm -r pkgbuilds
maybe `git clone`ing in `/tmp/` would be cleaner to avoid this line :thinking:

2022-09-30 18:10 UTC, amtoine commented on install.sh
> +cp .config/dmenu-flexipatch/patches.h dmenu
same remarks as above about `cd` and `/tmp/` :wink: 
(and there are trailing whitespaces here too :eyes:)

2022-09-30 18:27 UTC, atxr commented on .xinitrc
> +#!/bin/sh
Okay got it!
I added it to specify we use bspwm

2022-09-30 18:29 UTC, atxr commented on .xinitrc
> +twm &
Oupsi...

2022-09-30 18:29 UTC, atxr commented on install.sh
> +git clone --bare https://github.com/atxr/dotfiles-1 .dotfiles
Yes and I would like my repo lol
Maybe we should add an parameter to precise which fork to use?

2022-09-30 18:30 UTC, atxr commented on install.sh
> +/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME config --local status.showUntrackedFiles no
I already tried and it didn't work
I added an alias in this file but bash didn't recognise it
I found it weird and just gave up

2022-09-30 18:31 UTC, atxr commented on install.sh
> +./install.sh x86_64/paru x86_64/amtoine-scripts-git/ x86_64/amtoine-sounds-git/ x86_64/amtoine-wallpapers-git/ x86_64/amtoine-applications-git/ x86_64/amtoine-icons-git/
Maybe you should consider adding a parameter to quick install these one in amtoine/pkgbuils
Like `./install.sh --dotfiles`

2022-09-30 18:37 UTC, atxr commented on .xinitrc
> +#!/bin/sh
Fix [c6cbd5c](https://github.com/amtoine/dotfiles/pull/13/commits/c6cbd5c59ae933b5d315ee43ff3a77ec7e25de99)

2022-09-30 18:37 UTC, atxr commented on .xinitrc
> +twm &
Fix [c6cbd5c](https://github.com/amtoine/dotfiles/pull/13/commits/c6cbd5c59ae933b5d315ee43ff3a77ec7e25de99)

2022-09-30 18:38 UTC, atxr commented on install.sh
> +cp .config/dmenu-flexipatch/patches.h dmenu
Fix [3647001](https://github.com/amtoine/dotfiles/pull/13/commits/3647001dbead6820b4577d4d71ad34f8a2067f54)

2022-09-30 18:38 UTC, atxr commented on install.sh
> +sudo rm -r pkgbuilds
Fix [3647001](https://github.com/amtoine/dotfiles/pull/13/commits/3647001dbead6820b4577d4d71ad34f8a2067f54)

2022-09-30 18:38 UTC, atxr commented on install.sh
> +cd
Mmmm that's a good one thx
Fix [3647001](https://github.com/amtoine/dotfiles/pull/13/commits/3647001dbead6820b4577d4d71ad34f8a2067f54)

2022-10-01 12:03 UTC, amtoine commented on .xinitrc
> +#!/bin/sh
cool thanks :+1:

2022-10-01 12:06 UTC, amtoine commented on install.sh
> +git clone --bare https://github.com/atxr/dotfiles-1 .dotfiles
> Yes and I would like my repo lol Maybe we should add an parameter to precise which fork to use?
>
i think it's overkill

the two forks will have the same `main` branch, i.e. the branch used as the base to pull the dotfiles
it looks to me much easier to use the base repository as the default fork

in the end it really does not matter which one is used and adding a parameter does not look right to me :confused:

2022-10-01 12:07 UTC, amtoine commented on install.sh
> +/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME config --local status.showUntrackedFiles no
it really should work :thinking: 

```bash
#!/usr/bin/env bash

cmd="/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME"

$cmd status
```
works just fine and gives me
```bash
On branch personal/amtoine
Your branch is up to date with 'origin/personal/amtoine'.

nothing to commit (use -u to show untracked files)
```
couild you try that? :yum:

2022-10-01 12:09 UTC, amtoine commented on install.sh
> +./install.sh x86_64/paru x86_64/amtoine-scripts-git/ x86_64/amtoine-sounds-git/ x86_64/amtoine-wallpapers-git/ x86_64/amtoine-applications-git/ x86_64/amtoine-icons-git/
definitely a good idea, like that :yum:

for now, could you:
  - open an issue on https://github.com/amtoine/pkgbuilds
  - make this a multi-line until `--dotfiles` is available on `amtoine/pkgbuilds/install.sh`
  ?

  would be very helpful :relieved:

2022-10-01 12:12 UTC, amtoine commented on install.sh
> +cd
you used
```bash
{
    ...
}
```
instead of
```bash
(
    ...
)
```
:wink: 

here is an example
```bash
#!/usr/bin/env bash

(
    cd ~/ghq
    pwd
    ls
)

echo ""
pwd
ls
```
which gives me
```bash
/home/amtoine/ghq
github.com
gitlab.com

/home/amtoine
admin
dl
ghq
LICENSE
mail
media
misc
pkgs.toml
plan.md
README.md
worktree
```
:yum:

2022-10-01 12:13 UTC, amtoine commented on install.sh
> +sudo rm -r pkgbuilds
thanks :+1:

2022-10-01 12:15 UTC, amtoine commented
will review the few changes from [cccdda4](https://github.com/amtoine/dotfiles/pull/13/commits/cccdda434400d731bc8f03e5406313dfc4afd09c) right after the conversations above have been closed :wink:

2022-10-05 16:25 UTC, amtoine commented on install.sh
> +cd
looks there is a fix in https://github.com/goatfiles/dotfiles/pull/13/commits/5a2f3c51ad6d4fab878ca61c2cfb003faa3e8461

2022-10-05 16:25 UTC, amtoine commented on install.sh
> +./install.sh x86_64/paru x86_64/amtoine-scripts-git/ x86_64/amtoine-sounds-git/ x86_64/amtoine-wallpapers-git/ x86_64/amtoine-applications-git/ x86_64/amtoine-icons-git/
a fix in https://github.com/goatfiles/dotfiles/pull/13/commits/c07829b5f8e604e4d6e9dd0e03ce99be7ff66117 it appears :thinking:

2022-10-05 16:25 UTC, amtoine commented on install.sh
> +/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME config --local status.showUntrackedFiles no
did you try that? :thinking:

2022-10-18 09:15 UTC, atxr commented on install.sh
> +/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME config --local status.showUntrackedFiles no
See [1216087](https://github.com/goatfiles/dotfiles/pull/13/commits/1216087686400d6c11010f9ba39e51f34342fa5e)

2022-10-18 09:16 UTC, atxr commented on install.sh
> +/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME config --local status.showUntrackedFiles no
So we will have to push our `atxr` and `amtoine` branches to https://github.com/goatfiles/dotfiles?

2022-10-18 17:38 UTC, amtoine commented on install.sh
> +git clone --bare https://github.com/atxr/dotfiles-1 .dotfiles
perfect thanks :tada:

2022-10-18 17:39 UTC, amtoine commented on install.sh
> +/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME config --local status.showUntrackedFiles no
> See [1216087](https://github.com/goatfiles/dotfiles/pull/13/commits/1216087686400d6c11010f9ba39e51f34342fa5e)
>
seen thanks :muscle:

2022-10-18 17:40 UTC, amtoine commented on install.sh
> +/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME config --local status.showUntrackedFiles no
> So we will have to push our `atxr` and `amtoine` branches to https://github.com/goatfiles/dotfiles?
>
we should both have write access to [`goatfiles/dotfiles`](https://github.com/goatfiles/dotfiles), except for the `main` branch which is protected :yum: 
so yes, feel free to push :ok_hand:

2022-10-18 17:47 UTC, amtoine reviewed
that looks fine now :relieved: 

two last things:
- you do not check if the user is in his `$HOME` directory when executing `install`, but the script depends on it, **is that on purpose?** that's not a huge thing for now to be honest, just wanted to know :wink: 
- **have you tried this new version of the installation script?** not a big deal as it's a post-install script so bugs can be caught and fixed later


i'll approve when the questions have been answered :yum:

2022-10-19 10:58 UTC, atxr commented
I added `$HOME/` to the relative path in [cd936d4](https://github.com/goatfiles/dotfiles/pull/13/commits/cd936d459b9ad26cd4b93448cf0cf436744d41d5)
I'll test now and if no errors occur, I'll merge this branch!

2022-10-20 07:28 UTC, amtoine requested changes
a few more changes need to be applied to fix [cd936d4](https://github.com/goatfiles/dotfiles/pull/13/commits/cd936d459b9ad26cd4b93448cf0cf436744d41d5) :yum:

2022-10-20 07:28 UTC, amtoine commented on install.sh
> +git clone --bare https://github.com/goatfiles/dotfiles $HOME/dotfiles
should be `$HOME/.dotfiles` then, otherwise the following lines would not work :yum:

2022-10-20 07:28 UTC, amtoine commented on install.sh
> +nu -c "paru -S (open $HOME/pkgs.toml | get pkgs.pacman.explicit.package | find --invert --regex 'amtoine|wallpapers')"
as `nushell` is by construction a structured shell and programming language, the environment variables are structured as well
so you can not access `$HOME` like that :thinking: 

you have to use `$env.HOME` instead :wink: 

moreover, as you use it in a `string` expansion, you should use
```nu
$"($env.HOME)/pkgs.toml"
```

and to correct all the anoying `bash` quotes
```bash
nu -c 'open $"($env.HOME)/pkgs.toml" | get pkgs.pacman.explicit.package | find --invert --regex "amtoine|wallpapers"'
```
which seems to work in a `bash` shell`, so should work in the script as well :+1:

2022-10-20 07:28 UTC, amtoine commented on install.sh
> +(
if you add `$HOME` everywhere, maybe
```bash
(
    git clone ...
    cp $HOME/.config/...
    cd ...
    sudo make ...
)
```
would be better as well :thinking: 
even
```bash
git clone ...
cp $HOME/.config/...
(
    cd ...
    sudo make ...
)
```
'cause you do not need to enter the subshell before the `cd` :+1:

2022-11-02 09:44 UTC, amtoine commented on install.sh
> +git clone --bare https://github.com/goatfiles/dotfiles $HOME/dotfiles
appears to be in https://github.com/goatfiles/dotfiles/pull/13/commits/1e14604de6e3be2bd6dc7989a2a4217967f1ab40
thanks :ok_hand:

2022-11-02 10:08 UTC, atxr commented on install.sh
> +nu -c "paru -S (open $HOME/pkgs.toml | get pkgs.pacman.explicit.package | find --invert --regex 'amtoine|wallpapers')"
Fix [756aa03](https://github.com/goatfiles/dotfiles/pull/13/commits/756aa0344a387d0148a4cd8714a5abd8f108bd52)

2022-11-02 10:08 UTC, atxr commented on install.sh
> +(
Fix [9167df2](https://github.com/goatfiles/dotfiles/pull/13/commits/9167df2376a4a9fdefe2db52c952adf4ff2c49e8)

2022-11-02 10:09 UTC, atxr commented
The test was successful! Ready to merge :rocket:

2022-11-02 10:49 UTC, amtoine requested changes
> The test was successful! Ready to merge rocket
>
i tried the script in a fresh `arch` virtual machine, with `archinstall` and an "`xorg`" profile to have video drivers available :ok_hand: 

i see two issues which cause the script not to run properly :thinking: 
- `nushell` only lists the packages but does not call `paru` to install them
- i see an error with `X11.h` when `make`ing `dmenu-flexipatch`

2022-11-02 10:49 UTC, amtoine commented on install.sh
> +nu -c 'open $"($env.HOME)/pkgs.toml" | get pkgs.pacman.explicit.package | find --invert --regex "amtoine|wallpapers"'
https://github.com/goatfiles/dotfiles/pull/13/commits/756aa0344a387d0148a4cd8714a5abd8f108bd52 introduced a bug here

there is no `paru -S` anymore
hence `nu -c ...` will only list the packages of interest in `stdout` but never install them :thinking:

2022-11-02 10:49 UTC, amtoine commented on install.sh
> +    sudo make clean install
in the VM i introduce in this review, i have a "`X11/X11.h` missing" error and `dmenu` does not build :thinking: 

i dunno how you did run the script though :open_mouth:

2022-11-02 11:31 UTC, atxr commented on install.sh
> +nu -c 'open $"($env.HOME)/pkgs.toml" | get pkgs.pacman.explicit.package | find --invert --regex "amtoine|wallpapers"'
Which version of `paru` are you using?

2022-11-02 11:32 UTC, atxr commented on install.sh
> +    sudo make clean install
I have no idea about this, it worked on my VM with the same specs as yours. I need more details

2022-11-02 11:36 UTC, atxr commented on install.sh
> +nu -c 'open $"($env.HOME)/pkgs.toml" | get pkgs.pacman.explicit.package | find --invert --regex "amtoine|wallpapers"'
Fixed [497f5f1](https://github.com/goatfiles/dotfiles/pull/13/commits/497f5f1683824d37f9cfb4fb440a203c84d60b42)
My copy paste was too fast :)

2022-11-02 11:36 UTC, atxr commented on install.sh
> +    sudo make clean install
Maybe this is because of the missing `paru -S`?

2022-11-02 12:00 UTC, amtoine commented on install.sh
> +nu -c 'open $"($env.HOME)/pkgs.toml" | get pkgs.pacman.explicit.package | find --invert --regex "amtoine|wallpapers"'
this still is not correct :eyes:
`paru` does not take input from pipes :+1: 

for instance, with a dummy `deps.toml` as follows
```toml
[[pkgs.foo]]
package = "neofetch"
version = "neofetch-version"

[[pkgs.foo]]
package = "sd"
version = "sd-version"
```

```bash
nushell> paru -S (open deps.toml | get pkgs.foo.package | find neo)
```
does work but
```bash
nushell> open deps.toml | get pkgs.foo.package | find neo | paru -S
```
does not and shows
```bash
error: no targets specified (use -h for help)
```

2022-11-02 12:03 UTC, amtoine commented on install.sh
> +    sudo make clean install
> Maybe this is because of the missing `paru -S`?
>
mm maybe

but, with the current state of the script, you should not see `paru` install things...
`nu -c` only lists the dependencies but does not install them :thinking: 

that's quite confusing :confused:

2022-11-11 15:52 UTC, amtoine commented on install.sh
> +    sudo make clean install
i think it's due to my `/` partition being full :thinking: 

let's call that ok for now :wink:

2022-11-11 15:56 UTC, amtoine commented on install.sh
> +nu -c 'open $"($env.HOME)/pkgs.toml" | get pkgs.pacman.explicit.package | find --invert --regex "amtoine|wallpapers"'
should be ok in 7724a8c :ok_hand:

2022-11-11 15:58 UTC, amtoine approved these changes
oooook :smirk: 
now i think it's great and can be merged :wink:

2022-11-11 15:58 UTC, merged