add a bunch of new and better configurations
goatfiles/dotfiles pull request #15
Opened 2022-10-05 16:55 UTC by amtoine

This PR does the following things:
- add a basic config for [`broot`](https://github.com/Canop/broot)
- improve the `git` config with:
  - the `--verbose` flag on `git commit`
  - the `--branches --remotes --tags` flags on `git log` to remove the stashes in the tree
  - some basic worktree aliases
  - minor things
- add a basic config for [`helix`](https://github.com/helix-editor/helix)
- improve the [`nushell`](https://github.com/nushell/nushell) config with: 
  - some more aliases
  - enhanced output for `repo`
  - more robust behaviour in `vcfg`
  - the `cfgw` function to jump to worktrees inside _bare_ dotfiles
- add a basic dark config for the `okular` PDF viewer 
- move the `paru` config file to the location give in the `paru.conf (5)` `man` page
- start to track the list of mirrors for `pacman`
- add some sensible default to the `vim` config
- add the current list of system packages in `pkgs.toml`

@atxr,
if you could just have a look and see if everything is at least ok :relieved:

2022-10-18 13:08 UTC, atxr requested changes
These changes look good for me
I spotted some files that shouldn't be pushed into the main branch

2022-10-18 13:08 UTC, atxr commented on .config/git/config
> -  email = 44101798+AntoineStevan@users.noreply.github.com
I don't really like this `name` and `email` variable here
I think we shouldn't push this to the main branch
However, if it's only temporary, I'm ok with this.
But we should definitely read these variables from env variables, or set them during the installation script

2022-10-18 13:08 UTC, atxr commented on .config/qutebrowser/quickmarks
>  iris https://iris.isae.fr/acces-aux-ressources-de-calcul-de-l-isae-supaero
This file is personal, and should also be removed from the tracked files

2022-10-18 17:37 UTC, amtoine commented on .config/qutebrowser/quickmarks
>  iris https://iris.isae.fr/acces-aux-ressources-de-calcul-de-l-isae-supaero
same remark as above, this will have to be addressed somewhere :relieved:

2022-10-19 11:00 UTC, atxr commented on .config/qutebrowser/quickmarks
>  iris https://iris.isae.fr/acces-aux-ressources-de-calcul-de-l-isae-supaero
(you didn't do any remark above :eyes:)

2022-10-20 07:40 UTC, amtoine commented on .config/qutebrowser/quickmarks
>  iris https://iris.isae.fr/acces-aux-ressources-de-calcul-de-l-isae-supaero
(damn... did not send it...)

2022-10-20 07:42 UTC, amtoine commented on .config/git/config
> -  email = 44101798+AntoineStevan@users.noreply.github.com
i was simply saying that this is quite out of the scope of this PR :thinking: 

these dotfiles remain my personal config files until we decide to focus on that and change them...
this will be the topic for one or multiple issues :+1: 

it would imply way to much work to tackle that right now :open_mouth:

2022-11-13 09:32 UTC, amtoine commented
little ping there @atxr :wink:

2022-11-15 11:04 UTC, atxr commented
Thanks to our little discussion in private, I approve this PR :rocket:

2022-11-15 18:25 UTC, amtoine commented
> Thanks to our little discussion in private, I approve this PR rocket
>
cool :yum: 
that will be great for our personal branches :relieved:

2022-11-15 18:25 UTC, merged